### ISSUE TITLE
EventEmitter memory leak detected 

### ISSUE THREAD

**Issue by suhailgupta03** [website-scraper/node-website-scraper#231] opened 2017-08-25 10:09 UTC
I have been running the scraper when I got this message on the console:

`(node:19634) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit`

`const scrap = require('website-scraper');

let options = {
	urls: ['https://www.motormag.com.au/'],
	directory: '/home/suhail/test/dumps',
	recursive: true,
	maxRecursiveDepth: 5
};

scrap(options).then((result) => {
	console.log(result);
})
.catch((e) => console.log(e))
`

In a while got this error:
`<--- Last few GCs --->

[19634:0x23fd630]  2674916 ms: Mark-sweep 1400.1 (1644.9) -> 1399.5 (1644.9) MB, 50.5 / 0.0 ms  allocation failure GC in old space requested
[19634:0x23fd630]  2674978 ms: Mark-sweep 1399.5 (1644.9) -> 1399.5 (1644.9) MB, 55.3 / 0.0 ms  allocation failure GC in old space requested
[19634:0x23fd630]  2675054 ms: Mark-sweep 1399.5 (1644.9) -> 1399.4 (1643.4) MB, 65.9 / 0.0 ms  last resort 
[19634:0x23fd630]  2675120 ms: Mark-sweep 1399.4 (1643.4) -> 1399.3 (1643.4) MB, 66.5 / 0.0 ms  last resort 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x28df77993471 <JS Object>
    1: StringReplaceGlobalRegExpWithFunction(aka StringReplaceGlobalRegExpWithFunction) [native regexp.js:~256] [pc=0x2d23e8056c20](this=0x28df77982241 <undefined>,E=0x8b0901d2779 <String[48]: //www.googletagmanager.com/ns.html?id=GTM-TFSX6J>,y=0x15913fa33e41 <JS RegExp>,ak=0x348ba5f77891 <JS Function (SharedFunctionInfo 0x319a943702c9)>)
    2: RegExpReplace [native regexp.js:~356] [pc=0x2d23e...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x134e91c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [node]
 6: v8::internal::RegExpMacroAssemblerX64::GetCode(v8::internal::Handle<v8::internal::String>) [node]
 7: v8::internal::RegExpCompiler::Assemble(v8::internal::RegExpMacroAssembler*, v8::internal::RegExpNode*, int, v8::internal::Handle<v8::internal::String>) [node]
 8: v8::internal::RegExpEngine::Compile(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) [node]
 9: v8::internal::RegExpImpl::CompileIrregexp(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, bool) [node]
10: v8::internal::RegExpImpl::IrregexpPrepare(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>) [node]
11: v8::internal::RegExpImpl::GlobalCache::GlobalCache(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, v8::internal::Isolate*) [node]
12: 0x1145062 [node]
13: v8::internal::Runtime_RegExpExecMultiple(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x2d23e69840c7
Aborted (core dumped)
`

**Comment by s0ph1e** [comment] 2017-08-28 07:27
Hi @suhailgupta03 
Thanks for reporting issue

* As for event emitter - I'll check what is wrong with it
* As for memory - I believe it is because you are trying to download everything with depth = 5 so scraper may try to download whole internet :) I'd suggest to decrease `maxRecursiveDepth` and/or add `urlFilter` and/or increase memory limit for node process

Also you can check similar issues #215 #225

**Comment by fishcharlie** [comment] 2018-03-30 15:51
@s0ph1e Any updates on this? I'm getting this error about event emitter. Also in terms of memory, couldn't this library use streams to not use as much memory and just pipe it to the file system?

**Comment by s0ph1e** [comment] 2018-04-01 17:07
Hi @fishcharlie 
Unfortunately I was not able to debug this
I don't know easy ways to use streams instead of storing everything in memory because:
* this library not only saves files to fs but also modifies them
* to do modifications whole html/css file is needed in order to correctly parse it. I'm not sure how to do the same with chunk of file
* it needs previous results to perform next modifications - so need to store that data

**Comment by suhailgupta03** [comment] 2018-04-02 06:47
@fishcharlie You could try out a crawler I wrote a while ago. https://github.com/suhailgupta03/crawler

You could extend it the way you want. Try running the test file after you set up the directory structure and you will get an idea.

**Comment by fishcharlie** [comment] 2018-04-02 15:18
@s0ph1e, is it just a matter of not getting around to debugging it, or are you not able to find the problem? Like is it something you are still working on trying to figure out, or is it hopeless to get that resolved?

**Comment by fishcharlie** [comment] 2018-04-02 15:19
Sorry @suhailgupta03, but your packages documentation is pretty poor. I can't really follow what it does and how it works. I try to only use very well documented packages unless there is a very good reason to do otherwise.

**Comment by suhailgupta03** [comment] 2018-04-02 16:04
Sure. It was for a personal project. Not very well documented.

**Comment by s0ph1e** [comment] 2018-04-03 15:49
@fishcharlie I'm not able to reproduce `EventEmitter memory leak detected`. But I believe it is related to huge amount of downloaded content. 
All I can suggest for now - use `urlFilter` and decrease `maxRecursiveDepth`

If you have an idea how to reproduce/fix that - contributions are welcome

**Comment by s0ph1e** [comment] 2018-05-27 19:10
can not reproduce issue, close it for now

**Closed by s0ph1e** 2018-05-27 19:10 UTC
Labels: bug
