### ISSUE TITLE
Downloading if it is set as background image?

### ISSUE THREAD

**Issue by frontr-uk** [website-scraper/node-website-scraper#323] opened 2018-11-12 01:34 UTC
I have website that trying to save but in the code I see 

`<div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url('http://website.com/wp/edugrade/wp-content/uploads/2018/10/slide1.jpg'); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="http://website.com/wp/edugrade/wp-content/uploads/2018/10/slide1.jpg"></div>`

Is there a way to also save the background-image that is in the HTML referece if the domain is the same and than go Alter the HTML to reference from local  /img folder?

**Comment by s0ph1e** [comment] 2018-11-15 17:06
Hi @frontr-uk
Could you please share options object that you use?

By default, background images from css should be saved normally

**Comment by frontr-uk** [comment] 2018-11-20 22:22
Sure: 

var options = {
      urls:   req.body,
      urlFilter: function(url){
          return url.indexOf(req.body.urls.toString()) === 0;
      },
      recursive: true,
      maxDepth: 1,
      prettifyUrls: true,
      // filenameGenerator: 'bySiteStructure',
      directory: './site/',
      subdirectories: [
          {directory: 'svg', extensions: ['.svg']},
          {directory: 'img', extensions: ['.jpg', '.png']},
          {directory: 'js', extensions: ['.js']},
          {directory: 'css', extensions: ['.css']}
      ],
      sources: [
          {selector: 'img', attr: 'src'},
          {selector: 'img', attr: 'srcset'},
          {selector: 'link[rel="stylesheet"]', attr: 'href'},
          {selector: 'script', attr: 'src'},
          {selector: 'li', attr: 'data-thumb'},
          {selector: 'div', attr: 'data-thumb'}
      ],
      request: {
          headers: {
              'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19'
          }
      }
  }

**Comment by s0ph1e** [comment] 2018-11-21 09:20
@frontr-uk 
It should work if you add next elements to `sources` options:
```javascript
// this is for parsing css from elements with style attribute, f.e. <div style="css here">
{ selector: '[style]', attr: 'style' }, 
// this is for parsing css from <style> tag, also may be useful
{ selector: 'style' }, 
```

**Comment by frontr-uk** [comment] 2018-11-21 11:10
hmm getting bugs:

I set : 
```
var options = {
      urls:
          req.body.urls	// Will be saved with default filename 'index.html'
      ,
      urlFilter: function(url){
          console.log('url FAILS', url)
          return url.indexOf(req.body.urls[0].toString()) === 0;
      },

```
url FAILS color:%20#ffffff;
url FAILS margin-top:%20-80px;
url FAILS background-image:%20url(http://webdesign-finder.com/psycheco/wp-content/uploads/2017/10/shutterstock_561162460.jpg)
url FAILS background-image:%20url(http://webdesign-finder.com/psycheco/wp-content/uploads/2017/10/pricing-bg.jpg)
url FAILS margin-top:%20-60px;
err TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)

**Comment by s0ph1e** [comment] 2018-11-21 15:11
@frontr-uk could you provide url or html body of website which causes this error so I will be able to reproduce it?

**Comment by frontr-uk** [comment] 2018-11-23 15:18
same issue with this one: http://www.apusthemes.com/wp-demo/trucking
I get this error:
err TypeError: Parameter "url" must be a string, not object

It fails at the options

```
 var options = {
        urls: listofDomains
        	// Will be saved with default filename 'index.html'
        ,
        urlFilter: function(url){
            console.log('url', url)
            console.log(typeof url === 'string')
            if(typeof url === 'string'){
                return url.indexOf(urlDomain.toString()) === 0;
            }
....
```
        },

**Comment by frontr-uk** [comment] 2018-11-26 23:35
Hi @s0ph1e any feedback on this?

**Comment by s0ph1e** [comment] 2018-11-27 09:44
Hi @frontr-uk 

I was not able to reproduce urls like url `margin-top:%20-80px;` or  `color:%20#ffffff;`
I've tried with this code https://runkit.com/s0ph1e/5bf832c4312fc500122c1a9a. Did I miss something?

As I can see you are using `urls` array in `urlFilter` function and error says **Parameter "url" must be a string, not object**. Are you sure that `urls` array contain string? Maybe it contains object like `{url, filename}` and it causes error? 

Btw what package version are you using?

**Comment by frontr-uk** [comment] 2018-11-27 21:39
I was using npm package 'website-scraper-2', that had the option 
subdirectories: [
          {directory: 'svg', extensions: ['.svg']},
          {directory: 'img', extensions: ['.jpg', '.png']},
          {directory: 'js', extensions: ['.js']},
          {directory: 'css', extensions: ['.css']}
      ],

I see you don't have that in your code, to download the images.

**Comment by frontr-uk** [comment] 2018-11-27 22:22
also noticed for example in this website: 
http://demo.cmssuperheroes.com/themeforest/inbound-marketing/

that if it does not download all JS files especiall if the file ends like this "e.min.js?ver=4.9.8"

http://demo.cmssuperheroes.com/themeforest/inbound-marketing/wp-includes/js/wp-emoji-release.min.js?ver=4.9.8

**Comment by aivus** [comment] 2018-11-27 22:57
Hi @frontr-uk 

Package called `website-scraper-2` **is not related** to this repository.

You should contact @kauegimenes who is the maintainer of [website-scraper-2](https://www.npmjs.com/package/website-scraper-2) and ask him about that package.

This repository provides a package called [website-scraper](https://www.npmjs.com/package/website-scraper) as mentioned in repository description/readme file.

**Comment by kauegimenes** [comment] 2018-11-28 02:47
@frontr-uk you should use website-scraper not my wrapper (website-scraper-2) i'm not even sure why i created this fork.

**Comment by s0ph1e** [comment] 2018-11-29 10:03
As `Downloading background image` is no longer an issue - I'm closing it now

@frontr-uk if you find other problems on scraper's side - feel free to open new issues

**Closed by s0ph1e** 2018-11-29 10:03 UTC
