### ISSUE TITLE
Scrape files with exact same names when they include french characters

### ISSUE THREAD

**Issue by LucasDemea** [website-scraper/node-website-scraper#466] opened 2021-11-22 07:39 UTC
Hi,
I need the scraped files to have the exact same names as the original files. Instead, when the original filenames include french characters, I get:
`Capture-d’écran-2020-09-01-à-15.58.14.png`
becomes
`Capture-dâ__Ã©cran-2020-09-01-Ã -15.58.14.png`
Is there a way to preserve the exact original filenames ?

**Comment by s0ph1e** [comment] 2021-11-25 16:23
Hi @LucasDemea 

Sounds like a bug, I need to check this

I suggest to customize generateFilename action as described [here](https://github.com/website-scraper/node-website-scraper/blob/4.x/README.md#generatefilename) and try to receive correct filenames, hope it helps

**Comment by s0ph1e** [comment] 2021-12-28 11:24
I can confirm that this is a bug, root cause and possible workarounds are described in https://github.com/website-scraper/node-website-scraper/issues/454

We'll think how to fix it in future versions

**Comment by s0ph1e** [comment] 2022-06-09 12:08
The issue should be fixed by #482, the fix will be released in next version 5.1.0

**Comment by s0ph1e** [comment] 2022-06-11 12:39
Reopen because a version with a fix 5.1.0 was deprecated and reverted

**Closed** 2022-06-23 06:24 UTC
Labels: bug
